### ISSUE TITLE
text in plugins db entry

### ISSUE THREAD

**Issue by danmarsden** [annotate-co/moodle-block_annotate#17]
text in the plugins description looks a lot better now but I noticed this line:

"after adding the block to your course, all PDFs will have a button next to them"

should that be specifying "PDF" ? - looks like your plugin supports a range of different file-types.

**Comment by daniel-leon-gonzalez** [comment]
Thanks for your comment, that is a good point.

It is possible for us to convert a range of files (ppt, xls, jpg...) to PDF but this conversion is not currently enabled in the test server provided. The reason is that for most cases it is not necessary, as only PDF files are normally required to be annotated.

The conversion is enabled in www.annotate.co and could be added to a private install if it is required for a given organisation.
